// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheDeepOTools.Data;

namespace TheDeepOTools.Migrations.TheDeepOTools
{
    [DbContext(typeof(TheDeepOToolsContext))]
    [Migration("20210727065855_InventoryDB")]
    partial class InventoryDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheDeepOTools.Models.Inventory", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("ItemIdentifier")
                        .IsRequired();

                    b.Property<string>("ItemName")
                        .IsRequired();

                    b.Property<int>("OnHandQty");

                    b.Property<int>("OutQty");

                    b.Property<decimal>("Price");

                    b.Property<string>("Subcategory");

                    b.Property<int>("TotalQty");

                    b.HasKey("ItemID");

                    b.ToTable("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
